name: 自动混淆并发布到 Pages

on:
  push:
    branches: [main] # 如果您的主分支叫 master，请把这里改为 master

permissions:
  contents: write    # 必须开启写入权限

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - run: npm install
      
      - name: 修复权限并构建
        run: |
          chmod +x ./node_modules/.bin/javascript-obfuscator
          npm run build
      
      - name: 发布
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          force: true
